# -*- coding: utf-8 -*-
"""preprocessIOT23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5ZPMD7bdz9T8f4WsFRRoqANyqVTF28E
"""

import torch
import  pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from sklearn.model_selection import train_test_split
from google.colab import drive
drive.mount('/content/drive')
##########################
problem = 'MULTI'
##########READ DATA AVOIDING UNUSED COLUMN####
data = pd.read_csv('/content/drive/MyDrive/Data/iot23_combined_new.csv',index_col=0)
########Print class distribution and Dataframe dimensions ##########
print('Rows and columns of the dataset:',data.shape)
print('Distribution of labels:',data['label'].value_counts())
print('Distribution of labels:',data['label'].value_counts(normalize=True)*100)
print('Duration counts:',data['duration'].value_counts(dropna=False))

#input('WAIT')
###########
####Columns before########

print('Columns of dataset:',data.columns)
drop_columns = ['ts','uid','id.orig_h','id.resp_h','local_orig','local_resp','orig_ip_bytes','resp_ip_bytes','history']
###Drop###
data.drop(drop_columns,axis=1,inplace=True)
print('After dropping columns:',data.columns)
###Null values per column###
print('Null values:',data.isnull().sum())
#
#####Cleaning columns with mismatched values###
data['orig_bytes'] = pd.to_numeric(data['orig_bytes'],errors='coerce') #an ayto pou pao na kano noumero den einai arithmos to antikathista me NaN
data['resp_bytes'] = pd.to_numeric(data['resp_bytes'],errors='coerce')
data['duration'] = pd.to_numeric(data['duration'],errors='coerce')

data.info()
###Null values per column###
print('Null values:',data.isnull().sum())
#input('WAIT')
#### Replace null values with median value or mean or anything
data['orig_bytes'] = data['orig_bytes'].fillna(data['orig_bytes'].median()) #median/mean/mode etc
data['resp_bytes'] = data['resp_bytes'].fillna(data['resp_bytes'].median())
data['duration'] = data['duration'].fillna(data['duration'].median())
print('Null values again: ',data.isnull().sum())
##
#einai kai ta orig_bytes kai ta resp_bytes alla exoun mismatched(datatype) epeidh einai object. Tha kano convert se numeric

categorical_columns = data.select_dtypes(include=['object']).columns
numerical_columns = data.select_dtypes(exclude=['object']).columns
print(categorical_columns)
for column in numerical_columns:
    print(f"Counts of {column}:",data[column].value_counts(dropna=False))
for column in categorical_columns:
      print(f"Counts of {column}:",data[column].value_counts(dropna=False))


#input('WAIT')
numeric_data = data[numerical_columns]

##########CORRELATION MATRIX################
data_matrix = numeric_data.corr()
#############Graph heatmap###########
plt.figure(figsize=(12, 8))
sns.heatmap(data_matrix, annot=True, fmt=".2f", cmap="coolwarm", cbar=True)
plt.title("Correlation Matrix Heatmap")
plt.show()
###########SAVE TO CSV###############
#data.to_csv('/content/drive/MyDrive/Saves/cleaned.csv',index=False,mode='w')
#input('WAIT')
if problem == 'MULTI':
  data['label'] = data['label'].map({'Benign':0,'DDoS':1,'Okiru':2,'PartOfAHorizontalPortScan':3,'C&C':4,'C&C-HeartBeat':4,'C&C-FileDownload':4,'C&C-Torii':4,'C&C-Mirai':4,'C&C-HeartBeat-FileDownload':4}) #to attack poly geniko afaireitai
  #data['label'] = data['label'].map({'Benign':0,'DDoS':1,'Okiru':2,'PartOfAHorizontalPortScan':3}) #to attack poly geniko afaireitai
  data.dropna(axis=0,how='any',inplace=True) #If some categories are not included in the mapping they are removed
else:
  data['label'] = data['label'].apply(lambda x: 0 if x == 'Benign' else 1)
###DROP DUPLICATES###
data = data.drop_duplicates(keep='first')
#input('WAIT')
##############CONTEXT DICTIONARIES ########################
conn_state_dict = {'S0':'the originator tried to connect but the responder did not reply','S1':'the connection was established','S2':'the connection was established, the originator tried to close it but the responder did not reply','S3':'the connection was established, the responder tried to close it but the originator did not reply','SF':'the connection was established and terminated','SH':'the originator sent a SYN then a FIN but the responder did not send a SYN-ACK','SHR':'the responder sent a SYN-ACK then a FIN but the originator did not send a SYN','OTH':'no SYN observed','REJ':'the connection was rejected','RSTO':'the originator aborted the connection','RSTR':'the responder aborted the connection','RSTOS0':'the originator sent a SYN then a RST but the responder did not send a SYN-ACK','RSTRH':'the responder sent a SYN-ACK then a RST but the originator did not send a SYN'}
######CONVERT TO TEXT FOR TRANSFORMER/BERT-LIKE MODELS#############
sequences = []
def encode(entry):
    global sequences
    record = {}
    service = f"The application protocol utilized was {entry['service']}" if entry['service'] != '-' else f"The connection has no recorded application protocol"
    text = (
        f"This network flow shows a connection originating from port {entry['id.orig_p']} and destined to port {entry['id.resp_p']}. "
        f"{service}. "
        f"The connection lasted {entry['duration']} seconds. "
        f"The connection's transport layer protocol was {entry['proto']}. "
        f"The connection's state was set as {entry['conn_state']} meaning {conn_state_dict[entry['conn_state']]}. "
        f"The originator sent {entry['orig_bytes']} bytes of data, by sending {entry['orig_pkts']} packets. "
        f"The responder responded with {entry['resp_bytes']} bytes of data, by sending {entry['resp_pkts']} packets. "
        f"Packet loss was recorded as {entry['missed_bytes']} bytes.")
    record['text']  = text
    record['label'] = entry['label']
    sequences.append(record)
    return
#######APPLY ON EACH ROW AND CONVERT TO DATAFRAME AND SAVE#####
data.apply(encode, axis=1)
sequences = pd.DataFrame(sequences)
###
sequences.info()
print(sequences.shape)
print(sequences.head(1))

#sequences.to_csv('/content/drive/MyDrive/Saves/IoT23_sequences_binary.csv',index=False,mode='w')
sequences.to_csv('/content/drive/MyDrive/Saves/IoT23_sequences_multi.csv',index=False,mode='w')